spring.application.name=ONE-Backend-Assignment

# MySQL ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/one?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=one
spring.datasource.password='one_backend'